name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main  # Puedes cambiar esta rama por la que uses para producción

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Verificar el repositorio
      - name: Check out the repo
        uses: actions/checkout@v3

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construir y empujar la imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true  # Esto enviará la imagen a Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/mi-aplicacion-php:latest  # Cambia esto a tu nombre de usuario de Docker Hub y el nombre de la imagen
          file: ./Dockerfile  # Aquí especificas tu Dockerfile

